/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.simrtu.objectdb.explorer;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.simrtu.objectdb.explorer//obdbexplore//EN",
autostore = false)
@TopComponent.Description(preferredID = "obdbexploreTopComponent",
iconBase = "org/simrtu/objectdb/explorer/simRTU4_obdbexp.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.simrtu.objectdb.explorer.obdbexploreTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_obdbexploreAction",
preferredID = "obdbexploreTopComponent")
@Messages({
    "CTL_obdbexploreAction=Open ObjectDB Explorer",
    "CTL_obdbexploreTopComponent=ObjectDB Explorer",
    "HINT_obdbexploreTopComponent=ObjectDB Explorer"
})
public final class obdbexploreTopComponent extends TopComponent {

    public obdbexploreTopComponent() {
        initComponents();
        setName(Bundle.CTL_obdbexploreTopComponent());
        setToolTipText(Bundle.HINT_obdbexploreTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
